[package]
name = "squill"
version = "0.4.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Manage Postgresql database migrations"
homepage = "https://github.com/jdkaplan/squill"
repository = "https://github.com/jdkaplan/squill"
readme = "README.md"

[dependencies]
anyhow = "1.0.57"
chrono = { version = "0.4.24", features = ["serde"] }
clap = { version = "3.2.14", features = ["derive"] }
figment = { version = "0.10.7", features = ["env", "toml"] }
lazy_static = "1.4.0"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "postgres", "chrono", "uuid"] }
tabled = "0.10.0"
tera = { version = "1.17.1", default-features = false }
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
