[package]
name = "squill"
version = "0.5.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Database migrations for PostgreSQL"
homepage = "https://github.com/jdkaplan/squill"
repository = "https://github.com/jdkaplan/squill"
readme = "README.md"

include = [
    "src",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.3.14", features = ["derive"] }
figment = { version = "0.10.10", features = ["env", "toml"] }
lazy_static = "1.4.0"
regex = "1.9.1"
serde = { version = "1.0.171", features = ["derive"] }
sqlx = { version = "0.7.1", features = ["runtime-tokio-native-tls", "postgres", "time", "uuid"] }
tabled = "0.12.2"
tera = { version = "1.19.0", default-features = false }
thiserror = "1.0.43"
time = { version = "0.3.23", features = ["formatting", "serde"] }
tokio = { version = "1.29.1", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"

[dev-dependencies]
tempfile = "3.5.0"
uuid = { version = "1.4.1", features = ["v4", "serde"] }
