[package]
name = "squill"
version = "0.5.1"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Database migrations for PostgreSQL"
homepage = "https://github.com/jdkaplan/squill"
repository = "https://github.com/jdkaplan/squill"
readme = "README.md"

include = [
    "src",
    "LICENSE-APACHE",
    "LICENSE-MIT",
]

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.8", features = ["derive"] }
figment = { version = "0.10.12", features = ["env", "toml"] }
lazy_static = "1.4.0"
regex = "1.10.2"
serde = { version = "1.0.191", features = ["derive"] }
sqlx = { version = "0.7.2", features = ["runtime-tokio-native-tls", "postgres", "time", "uuid"] }
tabled = "0.14.0"
tera = { version = "1.19.1", default-features = false }
thiserror = "1.0.50"
time = { version = "0.3.30", features = ["formatting", "serde"] }
tokio = { version = "1.34.0", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber = "0.3.17"

[dev-dependencies]
tempfile = "3.5.0"
uuid = { version = "1.5.0", features = ["v4", "serde"] }
