[package]
name = "squill"
version = "0.4.2"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Manage Postgresql database migrations"
homepage = "https://github.com/jdkaplan/squill"
repository = "https://github.com/jdkaplan/squill"
readme = "README.md"

[dependencies]
anyhow = "1.0.70"
clap = { version = "4.1.11", features = ["derive"] }
figment = { version = "0.10.8", features = ["env", "toml"] }
lazy_static = "1.4.0"
regex = "1.7.1"
serde = { version = "1.0.147", features = ["derive"] }
sqlx = { version = "0.6.1", features = ["runtime-tokio-native-tls", "postgres", "time", "uuid"] }
tabled = "0.10.0"
tera = { version = "1.18.1", default-features = false }
thiserror = "1.0.40"
time = { version = "0.3.20", features = ["formatting", "serde"] }
tokio = { version = "1.26.0", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.16"
