pre-release-replacements = [
  {file="README.md", search="squill = .*", replace="{{crate_name}} = \"{{version}}\""},

  {file="CHANGELOG.md", search="## Unreleased", replace="## Unreleased\n\n## {{version}} - {{date}}"},
]
