name: PR

on:
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.70
        with:
          components: rustfmt

      - run: cargo fmt --all --check

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.70
        with:
          components: clippy

      - uses: Swatinem/rust-cache@v2

      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@1.70

      - uses: Swatinem/rust-cache@v2

      - run: cargo test --workspace --no-fail-fast
        env:
          PGUSER: 'postgres'
          PGPASSWORD: 'password'
          PGHOST: 'localhost'
          PGPORT: '5432'
